### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by ForteScarlet** [simple-robot/simpler-robot#133]
目前版本暴露的问题越来越多。考虑重新设计项目结构。
- [x] 重构为gradle project
- [x] api模块
- [x] 核心模块
- [x] 组件模块
    - [x] QQ频道
    - [x] mirai
    - [x] KOOK 
    - [x] 组件协同

**Comment by ForteScarlet** [comment]
放弃仍旧站在Java和QQ的立场上思考API的方式，尝试以宏观视角

**Comment by ForteScarlet** [comment]
应考虑赋予`Bot`更多职能
考虑更抽象的概念

**Comment by HuPeng333** [comment]
如果真有3.0 希望能少抛一点RuntimeException，已经踩了好多坑了:(

*昨天刚把自己机器人写完，已经没有什么bug了，然后把机器人挂服务器上了。中途把测试群解散了(因为功能已经差不多了)，结果一个定时任务中要用GETTER获取机器人加入的群，即使那个群已经被解散了，但还是获取到了那个群，接着让机器人对这个群发消息，直接抛了一个RuntimeException强行把循环终止了，刚好这个群排序还靠前，直接让定时任务作废了,,,*

**Comment by ForteScarlet** [comment]
> 如果真有3.0 希望能少抛一点RuntimeException，已经踩了好多坑了:(
> 
> _昨天刚把自己机器人写完，已经没有什么bug了，然后把机器人挂服务器上了。中途把测试群解散了(因为功能已经差不多了)，结果一个定时任务中要用GETTER获取机器人加入的群，即使那个群已经被解散了，但还是获取到了那个群，接着让机器人对这个群发消息，直接抛了一个RuntimeException强行把循环终止了，刚好这个群排序还靠前，直接让定时任务作废了,,,_

你这问题听上去，归根结底是mirai会获取已解散群聊的bug。你可以考虑在循环体内try-catch以保证循环本身正常，或者发起一个新的issue并提供相关错误日志。
当然，未来版本会考虑优化这些情况，但是运行时异常很难说会变少

**Comment by HuPeng333** [comment]
不过这个感觉要踩一次坑，才会知道要catch哪个Exception，确实感觉有点难受

**Comment by ForteScarlet** [comment]
> 不过这个感觉要踩一次坑，才会知道要catch哪个Exception，确实感觉有点难受

嗯..这个确实，但是实际上假若把所有异常变成受检异常也会在另一个层面很难受，只能说会更加完善注释说明，所有可能的异常都会提前说明

**Comment by ForteScarlet** [comment]
21/10/5
- 重构为 `gradle` 项目。
- 旧设计暴露出的问题日益严重，而只身一人维护庞大的项目与其所得之间的天平开始摇摆。
在思考 `v3.0.0` 设计的同时需要考虑其他方面的事情了。

**Comment by sleepinginsummer** [comment]
想问个问题，3.0里面如何不通过定时任务或者监听，直接向某个qq发消息，2.0可以通过启动类实现SimbotProcess 接口 获取到context。3.0有类似的方法吗

**Comment by ForteScarlet** [comment]
> 想问个问题，3.0里面如何不通过定时任务或者监听，直接向某个qq发消息，2.0可以通过启动类实现SimbotProcess 接口 获取到context。3.0有类似的方法吗

请在独立issue中发起新疑问

**Comment by ForteScarlet** [comment]
beta已临近喵，希望如此。

**Comment by ForteScarlet** [comment]
初次稳定版已经接近

**Comment by ForteScarlet** [comment]
- https://github.com/simple-robot/simpler-robot/pull/662
